export const destinationsData = [
  {
    name: 'Chitrakote Waterfall',
    slug: 'chitrakote-waterfall',
    district: 'Bastar',
    location: 'Jagdalpur, Bastar District',
    category: 'Waterfall',
    description: "Widely known as the 'Niagara of India', Chitrakote is the widest waterfall in India, cascading down 95 feet on the Indravati River. During monsoons, its horse-shoe shape presents a roaring spectacle with misty rainbows.",
    image: 'https://images.unsplash.com/photo-1544644181-1484b3fdfc62?auto=format&fit=crop&w=1200&q=80',
    bestTimeToVisit: 'July to February',
    entryFee: 0,
    coordinates: { lat: 19.2066, lng: 81.7061 },
  },
  {
    name: 'Tirathgarh Waterfall',
    slug: 'tirathgarh-waterfall',
    district: 'Bastar',
    location: 'Kanger Valley National Park, Bastar',
    category: 'Waterfall',
    description: 'A stunning multi-tiered cascade where the Mugabahar River plummets over 300 feet down layered rock formations, surrounded by the lush green canopy of the Kanger Valley.',
    image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80',
    bestTimeToVisit: 'October to March',
    entryFee: 25,
    coordinates: { lat: 18.9161, lng: 81.8631 },
  },
  {
    name: 'Sirpur Heritage Site',
    slug: 'sirpur-heritage-site',
    district: 'Mahasamund',
    location: 'Sirpur, Mahasamund District',
    category: 'Historical',
    description: 'An ancient capital of South Kosala along the Mahanadi river, Sirpur houses 5th-8th century brick temples like the famous Lakshmana Temple, Gandheshwar Temple, and extensive excavated Buddhist monasteries visited by Hiuen Tsang.',
    image: 'https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?auto=format&fit=crop&w=1200&q=80',
    bestTimeToVisit: 'November to February',
    entryFee: 40,
    coordinates: { lat: 21.3432, lng: 82.1772 },
  },
  {
    name: 'Bhoramdeo Temple',
    slug: 'bhoramdeo-temple',
    district: 'Kabirdham',
    location: 'Chhapri, Kawardha, Kabirdham',
    category: 'Historical',
    description: "Celebrated as the 'Khajuraho of Chhattisgarh', this 11th-century Nagara-style stone temple built by the Nagavanshi dynasty is nestled in the foothills of the Maikal range, featuring intricate erotic and mythological carvings.",
    image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80',
    bestTimeToVisit: 'October to March',
    entryFee: 0,
    coordinates: { lat: 22.1192, lng: 81.1578 },
  },
  {
    name: 'Barnawapara Wildlife Sanctuary',
    slug: 'barnawapara-wildlife-sanctuary',
    district: 'Baloda Bazar',
    location: 'Baloda Bazar District',
    category: 'Wildlife',
    description: 'Covering 245 sq km of mixed dry deciduous and sal forests, Barnawapara is renowned for sightings of leopards, Indian bison (gaur), barking deer, sloth bears, wild boars, and over 150 species of birds.',
    image: 'https://images.unsplash.com/photo-1534188753412-3e26d0d618d6?auto=format&fit=crop&w=1200&q=80',
    bestTimeToVisit: 'November to June',
    entryFee: 100,
    coordinates: { lat: 21.4116, lng: 82.4173 },
  },
  {
    name: 'Mainpat Hill Station',
    slug: 'mainpat-hill-station',
    district: 'Surguja',
    location: 'Surguja District',
    category: 'Nature',
    description: "Affectionately called the 'Shimla of Chhattisgarh', Mainpat is a picturesque hill plateau known for Tibetan settlements, Dhakpo Shedrupling Monastery, the bouncy Jaljali marshland, and Tiger Point waterfall.",
    image: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1200&q=80',
    bestTimeToVisit: 'Throughout the year (ideal in Winter)',
    entryFee: 0,
    coordinates: { lat: 22.8122, lng: 83.2847 },
  },
  {
    name: 'Kanger Valley & Kutumsar Caves',
    slug: 'kanger-valley-and-kutumsar-caves',
    district: 'Bastar',
    location: 'Jagdalpur, Bastar',
    category: 'Adventure',
    description: "One of India's most biodiverse national parks, featuring subterranean limestone caves (Kutumsar, Dandak, Kailash) with natural stalactites and stalagmites, and home to the state bird: the Bastar Hill Myna.",
    image: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=1200&q=80',
    bestTimeToVisit: 'November to May',
    entryFee: 50,
    coordinates: { lat: 18.8687, lng: 81.9427 },
  },
  {
    name: 'Maa Danteshwari Temple',
    slug: 'danteshwari-temple',
    district: 'Dantewada',
    location: 'Dantewada Town',
    category: 'Religious',
    description: 'One of the revered 52 Shaktipeeths of Goddess Sati, situated at the confluence of the sacred Shankini and Dankini rivers. It is the focal spiritual center for the grand 75-day Bastar Dussehra celebration.',
    image: 'https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=1200&q=80',
    bestTimeToVisit: 'September to March',
    entryFee: 0,
    coordinates: { lat: 18.8924, lng: 81.3508 },
  },
];

export const usersData = [
  // Admin Account
  {
    name: 'Chhattisgarh Tourism Admin',
    email: 'admin@cg.gov.in',
    password: 'adminpassword123',
    role: 'admin',
    phone: '+91 77124 10001',
    profileImage: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=400&q=80',
  },
  // Tourists
  {
    name: 'Rahul Sharma',
    email: 'rahul@example.com',
    password: 'tourist123',
    role: 'tourist',
    phone: '+91 98271 22334',
    profileImage: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=400&q=80',
  },
  {
    name: 'Priya Verma',
    email: 'priya@example.com',
    password: 'tourist123',
    role: 'tourist',
    phone: '+91 97551 88990',
    profileImage: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=400&q=80',
  },
  // Guides
  {
    name: 'Ramesh Baghel',
    email: 'ramesh.bastar@example.com',
    password: 'guide123',
    role: 'guide',
    phone: '+91 94252 11001',
    profileImage: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80',
    guideInfo: {
      bio: 'Bastar native with 8 years of experience guiding tourists through Chitrakote, Tirathgarh, and traditional tribal weekly haats (markets). Fluent in Halbi, Gondi, Hindi and English.',
      experience: 8,
      languages: ['Hindi', 'Chhattisgarhi', 'Halbi', 'English'],
      locationsServed: ['Bastar', 'Dantewada'],
      specializations: ['Waterfalls & Trekking', 'Cultural & Tribal', 'Adventure'],
      pricePerDay: 1800,
      availability: true,
      rating: 4.9,
      reviewCount: 14,
      isVerified: true,
    },
  },
  {
    name: 'Sunita Markam',
    email: 'sunita.markam@example.com',
    password: 'guide123',
    role: 'guide',
    phone: '+91 94060 44552',
    profileImage: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=400&q=80',
    guideInfo: {
      bio: 'Eco-tourism and cave exploration specialist for Kanger Valley National Park. Certified naturalist passionate about wildlife conservation and birdwatching.',
      experience: 5,
      languages: ['Hindi', 'Chhattisgarhi', 'English'],
      locationsServed: ['Bastar'],
      specializations: ['Wildlife & Nature', 'Adventure'],
      pricePerDay: 1500,
      availability: true,
      rating: 4.8,
      reviewCount: 9,
      isVerified: true,
    },
  },
  {
    name: 'Devendra Patel',
    email: 'devendra.heritage@example.com',
    password: 'guide123',
    role: 'guide',
    phone: '+91 98263 77881',
    profileImage: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80',
    guideInfo: {
      bio: 'Archaeology enthusiast specializing in Sirpur Buddhist monuments and the ancient architecture of Bhoramdeo Temple. Member of the State Archaeological Tourism Guild.',
      experience: 10,
      languages: ['Hindi', 'Chhattisgarhi', 'English'],
      locationsServed: ['Mahasamund', 'Kabirdham', 'Raipur'],
      specializations: ['Historical & Heritage', 'Spiritual & Religious'],
      pricePerDay: 2200,
      availability: true,
      rating: 4.9,
      reviewCount: 19,
      isVerified: true,
    },
  },
  {
    name: 'Amit Beck',
    email: 'amit.mainpat@example.com',
    password: 'guide123',
    role: 'guide',
    phone: '+91 91310 99223',
    profileImage: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=400&q=80',
    guideInfo: {
      bio: 'Local explorer from Surguja offering trekking, camping, and cultural tours of the Mainpat Tibetan settlements and Jaljali marshlands.',
      experience: 4,
      languages: ['Hindi', 'Chhattisgarhi'],
      locationsServed: ['Surguja', 'Baloda Bazar'],
      specializations: ['Nature', 'Adventure'],
      pricePerDay: 1300,
      availability: true,
      rating: 4.7,
      reviewCount: 7,
      isVerified: true,
    },
  },
];
